// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDtmGRJ9ozVd858p8u-R3tMwP22cxe94',
    appId: '1:472380581400:web:fb4a5f62a0a6c923af856d',
    messagingSenderId: '472380581400',
    projectId: 'spotify-3ad39',
    authDomain: 'spotify-3ad39.firebaseapp.com',
    storageBucket: 'spotify-3ad39.appspot.com',
    measurementId: 'G-EFDY2JKP7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_gzPu32_ZOF96Y7VoIuAl-rCJUZO634',
    appId: '1:472380581400:android:4a290abd922b1433af856d',
    messagingSenderId: '472380581400',
    projectId: 'spotify-3ad39',
    storageBucket: 'spotify-3ad39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrLd0QSCcQRmLL0nDmkcnvvjGH9p4wFPk',
    appId: '1:472380581400:ios:532e8f2a693b0faeaf856d',
    messagingSenderId: '472380581400',
    projectId: 'spotify-3ad39',
    storageBucket: 'spotify-3ad39.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrLd0QSCcQRmLL0nDmkcnvvjGH9p4wFPk',
    appId: '1:472380581400:ios:532e8f2a693b0faeaf856d',
    messagingSenderId: '472380581400',
    projectId: 'spotify-3ad39',
    storageBucket: 'spotify-3ad39.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSDtmGRJ9ozVd858p8u-R3tMwP22cxe94',
    appId: '1:472380581400:web:8fe4ea8188ebfc44af856d',
    messagingSenderId: '472380581400',
    projectId: 'spotify-3ad39',
    authDomain: 'spotify-3ad39.firebaseapp.com',
    storageBucket: 'spotify-3ad39.appspot.com',
    measurementId: 'G-9DPDHPLS0Z',
  );
}
